# Поддержка версии Python
target-version = "py312"

# Основные настройки
line-length = 120 # Максимальная длина строки для кода
indent-width = 4 # Ширина отступа

# Каталоги, которые следует учитывать при разрешении импорта из first/third-party источников
src = ["src"]

# Настройки линтера
[lint]

# Нестабильные и находящиеся в предварительной версии правила
preview = true

# Правила, которые должен применять линтер
select = [
    "RUF",  # Ruff
]

# Игнорирование конкретных предупреждений линтера
ignore = [
    "RUF001", # Игнорирование похожих символов с разными ASCII
    "RUF002", # Игнорирование похожих символов с разными ASCII
    "RUF003", # Игнорирование похожих символов с разными ASCII
]

# Исключение директорий и файлов из линтинга
exclude = [
]

# Настройки форматтера
[format]
quote-style = "double" # 'single' для одинарных, "double" для двойных кавычек
indent-style = "space"
